# Generated by Django 5.1.6 on 2025-03-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_orderitem_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('cash', 'Cash on Delivery')], default='card', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('cash', 'Cash on Delivery')], default='card', max_length=20),
        ),
    ]
