# Generated by Django 5.1.6 on 2025-04-25 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_bouquetshape_flower_greenery_wrappingpaper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_bouquet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.custombouquet'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
