# Generated by Django 5.1.6 on 2025-04-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_product_custom_bouquet_product_is_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auction_drop_amount',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='auction_floor_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='auction_interval_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='product',
            name='auction_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='auction_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='in_store',
            field=models.BooleanField(default=False),
        ),
    ]
