# Generated by Django 5.1.6 on 2025-05-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_product_auction_drop_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_fee',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Flowers', 'Flowers'), ('Bouquets', 'Bouquets'), ('Accessories', 'Accessories'), ('Gifts', 'Gifts'), ('CustomBouquet', 'CustomBouquet')], default='General', max_length=100),
        ),
    ]
