# Generated by Django 5.1.6 on 2025-05-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_remove_order_delivery_fee_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
