# Generated by Django 5.1.6 on 2025-05-01 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombouquet',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_custom_bouquet', to='App.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='custom_bouquet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_product', to='App.custombouquet'),
        ),
    ]
