# Generated by Django 5.1.6 on 2025-05-01 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_custombouquet_product_alter_product_custom_bouquet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='custom_bouquet',
        ),
    ]
