# Generated by Django 5.1.6 on 2025-05-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_remove_product_custom_bouquet'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='before_auction_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='bid_submited',
            field=models.BooleanField(default=False),
        ),
    ]
