# Generated by Django 5.1.6 on 2025-05-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_purcheses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
