# Generated by Django 5.1.6 on 2025-05-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('buchete', 'buchete'), ('plante', 'plante'), ('aranjamente', 'aranjamente'), ('Accessories', 'Accessories'), ('Gifts', 'Gifts'), ('CustomBouquet', 'CustomBouquet')], default='General', max_length=100),
        ),
    ]
