# Generated by Django 5.1.6 on 2025-05-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auction_item_is_in_cart',
            field=models.BooleanField(default=False),
        ),
    ]
