# Generated by Django 5.1.6 on 2025-05-11 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_product_auction_item_is_in_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='auction_item_is_in_cart',
        ),
    ]
