# Generated by Django 5.1.6 on 2025-05-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_remove_product_auction_item_is_in_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('path', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
