# Generated by Django 5.1.6 on 2025-07-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_visitorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrappingpaper',
            name='color',
            field=models.CharField(blank=True, help_text='Hex color code, e.g. #FFFFFF', max_length=7, null=True),
        ),
    ]
