# Generated by Django 5.1.6 on 2025-07-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_wrappingpaper_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrappingColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hex', models.CharField(max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='wrappingpaper',
            name='color',
        ),
        migrations.AddField(
            model_name='wrappingpaper',
            name='colors',
            field=models.ManyToManyField(related_name='wrappings', to='App.wrappingcolor'),
        ),
    ]
