# Generated by Django 5.1.6 on 2025-07-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_wrappingcolor_remove_wrappingpaper_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrappingpaper',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
