# Generated by Django 5.1.6 on 2025-07-30 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0031_wrappingpaper_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrappingpaper',
            name='colors',
        ),
        migrations.CreateModel(
            name='WrappingPaperColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_stock', models.BooleanField(default=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.wrappingcolor')),
                ('wrapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='App.wrappingpaper')),
            ],
        ),
    ]
