# Generated by Django 5.1.6 on 2025-07-30 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_remove_wrappingpaper_colors_wrappingpapercolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrappingpapercolor',
            name='wrapping',
        ),
        migrations.AddField(
            model_name='wrappingpaper',
            name='colors',
            field=models.ManyToManyField(through='App.WrappingPaperColor', to='App.wrappingcolor'),
        ),
        migrations.AddField(
            model_name='wrappingpapercolor',
            name='wrapping_paper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.wrappingpaper'),
        ),
    ]
