# Generated by Django 5.1.6 on 2025-07-30 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0033_remove_wrappingpapercolor_wrapping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrappingpapercolor',
            name='wrapping_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='App.wrappingpaper'),
        ),
    ]
