# Generated by Django 5.1.6 on 2025-07-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0034_alter_wrappingpapercolor_wrapping_paper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrappingpapercolor',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='wrappingpapercolor',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
