# Generated by Django 5.1.6 on 2025-08-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0036_alter_product_description_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
