# Generated by Django 5.1.6 on 2025-08-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0037_contactmessage_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
