# Generated by Django 5.1.6 on 2025-08-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0040_order_delivery_notes_order_delivery_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time_slot',
            field=models.CharField(blank=True, choices=[('09:00-11:00', '09:00 - 11:00'), ('11:00-13:00', '11:00 - 13:00'), ('13:00-15:00', '13:00 - 15:00'), ('15:00-17:00', '15:00 - 17:00'), ('17:00-19:00', '17:00 - 19:00'), ('19:00-21:00', '19:00 - 21:00')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=29.0, max_digits=10),
        ),
    ]
