# Generated by Django 5.1.6 on 2025-09-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0041_order_delivery_time_slot_alter_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['timestamp'], name='App_visitor_timesta_78429d_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['path'], name='App_visitor_path_6bcd95_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['session_key', 'timestamp'], name='App_visitor_session_b8b274_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['session_key', 'path', 'timestamp'], name='App_visitor_session_658730_idx'),
        ),
    ]
